services:
  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py init_system &&
             gunicorn ventas.wsgi:application --bind 0.0.0.0:8001 --workers 2"
    ports:
      - "8001:8001"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media

volumes:
  media_data:
  static_data: