from django.urls import path

from app.catalog.views import catalog, inicio

urlpatterns = [
    path('', inicio.CatalogView, name='CatalogView'),
    path('detail_product/<int:id_producto>/', inicio.optenerProducto, name='detail_product'),
    path('ver_carrito/', inicio.ver_carrito, name='ver_carrito'),
    path('show_productos_carrito/', inicio.show_productos_carrito, name='show_productos'),
    path('vaciar_carrito/', inicio.vaciar_carrito, name='vaciar_carrito'),
    path('eliminarProducto/<int:id_producto>/', inicio.eliminarProducto, name='eliminarProducto'),
    path('actualizarCantidad/', inicio.actualizarCantidad, name='actualizarCantidad'),
    path('shear_product/', inicio.shear_product, name='shear_product'),
    path('mostrar_por_categoria/<int:id_categoria>/', inicio.mostrar_por_categoria, name='mostrar_por_categoria'),
    path('confirmar_compra/', inicio.confirmar_compra, name='confirmar_compra'),
    path('new_producto/', inicio.newProducto, name='new_producto'),
    path('new_category/', inicio.newCategory, name='new_category'),
    path('updateProduct/<int:id_product>/', inicio.updateProduct, name='updateProduct'),
    path('deleteProduct/<int:id_product>/', inicio.deleteProduct, name='deleteProduct'),
    path('updateStock/<int:id_product>/', inicio.updateStock, name='updateStock'),
    path('imgs_products/<int:id_producto>/', inicio.imgs_products, name='imgs_products'),
    path('remode_imgs_products/<int:id_producto>/', inicio.remode_imgs_products, name='remode_imgs_products'),
    path('deleteImgProduct/<int:id_img>/', inicio.deleteImgProduct, name='deleteImgProduct'),
    path('getPrecioEnvio/', inicio.getPrecioEnvio, name='get_precios'),
    path('form_sheart_product/', inicio.form_sheart_product, name='form_sheart_product'),

    # rutas de las vistas inicio
    path('login_user/', inicio.login_user, name='login_user'),
    path('salir/', inicio.salir, name='salir'),
    path('validar_form/', inicio.validar_form, name='validar_form'),
    path('registrar_afiliado/', inicio.registrar_afiliado, name='registrar_afiliado'),
    path('add_huvicacion/', inicio.add_huvicacion, name='add_huvicacion'),
    path('configuraciones/', inicio.configuraciones_company, name='configuraciones'),
    path('precio_envio/', inicio.precio_envio, name='precio_envio'),
    path('buscar_orden/', inicio.buscar_orden, name='buscar_orden'),
    path('add_avisos/', inicio.add_avisos, name='add_avisos'),
    path('get_opciones/', inicio.get_opciones, name='get_opciones'),
    path('del_precio/<int:id_precio>/', inicio.del_precio, name='del_precio'),
    path('banco_envio/', inicio.banco_envio, name='banco_envio'),
    path('infor_banco/', inicio.infor_banco, name='infor_banco'),
    path('del_infor_banco/<int:id_banco>/', inicio.del_infor_banco_by_company, name='del_infor_banco_by_company'),
    path('eliminar_opciones/<int:id_aviso>/', inicio.eliminar_opciones, name='eliminar_opciones'),
    path('orden/print/<int:id_orden>/', inicio.print_orden, name='print_orden'),
    path('like/<int:id_orden>/<int:id_cliente>/', inicio.like_company, name='like'),
    path('report_by_date/', inicio.reportByRange, name='reportByRange'),
    path('inventario_productos/', inicio.inventarioProductos, name='inventario_productos'),
    path('reporte_form/<str:criterio>/', inicio.reporte_form, name='reporte_form'),
    path('productos_pdf/<str:criterio>/', inicio.reporte_inventario, name='inventario_productos'),
    path('info_address_company/', inicio.info_address_company, name='info_address_company'),
    path('del_address_comp/<int:id_address>/', inicio.del_address_comp, name='del_address_comp'),
    path('add_condiciones/', inicio.add_condiciones, name='add_condiciones'),
    path('get_condiciones/', inicio.get_condiciones, name='get_condiciones'),
    path('delete_regla/<int:id_regla>/', inicio.delete_regla, name='delete_regla'),
    path('suscribirse/', inicio.suscribirse, name='suscribirse'),
    path('estado_company/', inicio.estadoCompany, name='estado_company'),
    path('autorizar/<int:id_orden>/', inicio.autorizar_orden, name='autorizar_orden'),
    path('catalogo/<slug:slug>/', inicio.redirigir_a_catalogo, name='redirigir_a_catalogo'),

    path('informacion_web/', inicio.informacion_web, name='informacion_web'),
    path('informacion_empresa/', inicio.informacion_empresa, name='informacion_empresa'),

    path('add_red_social/', inicio.add_red_social, name='add_red_social'),
    path('get_redes_sociales/', inicio.get_redes_sociales, name='get_redes_sociales'),
    path('delete_red_social/<int:id_red_social>/', inicio.delete_red_social, name='delete_red_social'),
    path('info_afiliado/<int:id_afiliado>/', inicio.info_afiliado, name='info_afiliado'),

    path('cambiar_estado/<int:id_orden>/', inicio.cambiar_estado, name='cambiar_estado'),
]
