from app.tiendas import views
from django.urls import path

urlpatterns = [
    path('<int:id_type>/type/', views.getTypes, name='type'),
    path('<int:id_ciudad>/city/', views.getCiudades, name='city'),
    path('registro_company/', views.registro_company, name='registro_company'),
    path('crear_tienda/<int:id_usuario>', views.crearNuevaTienda, name='crear_tienda'),
    path('validar_form/', views.validar_form, name='validar_form'),
    path('validar_username/', views.validar_username, name='validar_username'),
    path('login_user/', views.login_user, name='login_user'),
    path('salir/', views.salir, name='salir'),
    path('<int:id_plan>/get_img/', views.get_img_plan, name='get_img_plan'),
    path('register_data/', views.datos_registro, name='datos_registro'),
    path('new_store/', views.new_store, name='new_store'),
    path('<int:user_id>/companys/', views.companys_from_user, name='companys_from_user'),
    path('redirigir-a-companys/', views.redirigir_a_companys, name='redirigir_a_companys'),
    path('<int:id_company>/updateCompany/', views.updateCompany, name='updateCompany'),
    path('<int:id_company>/add_images_company/', views.add_images_company, name='add_images'),
    path('<int:id_company>/deleteCompany/', views.deleteCompany, name='deleteCompany'),
    path('<int:id_company>/createDonimio/', views.create_dominio, name='create_dominio'),
    path('<slug:slug>/', views.redirigir_a_catalogo, name='redirigir_a_catalogo'),
    path('<int:id_company>/add_huvicacion/', views.add_huvicacion, name='add_huvicacion'),
    path('<int:id_company>/configuraciones', views.configuraciones_company, name='configuraciones'),
    path('<int:id_company>/precio_envio', views.precio_envio, name='precio_envio'),
    path('<int:id_company>/buscar_orden', views.buscar_orden, name='buscar_orden'),
    path('<int:id_company>/add_avisos', views.add_avisos, name='add_avisos'),
    path('<int:id_company>/get_opciones', views.get_opciones, name='get_opciones'),
    path('<int:id_precio>/del_precio', views.del_precio, name='del_precio'),
    path('<int:id_company>/banco_envio', views.banco_envio, name='banco_envio'),
    path('<int:id_company>/infor_banco', views.infor_banco, name='infor_banco'),
    path('<int:id_banco>/del_infor_banco_by_company', views.del_infor_banco_by_company, name='del_infor_banco_by_company'),
    path('<int:id_aviso>/eliminar_opciones', views.eliminar_opciones, name='eliminar_opciones'),
    
    path('orden/<int:id_company>/<int:id_orden>/print/',views.print_orden,name='print_orden'),
    path('<int:id_company>/<int:id_orden>/<int:id_cliente>/like', views.like_company, name='like'),
    path('<int:id_company>/report_by_date', views.reportByRange, name='reportByRange'),
    path('<int:id_company>/inventario_productos', views.inventarioProductos, name='inventario_productos'),
    path('<int:id_company>/<str:criterio>/reporte_form', views.reporte_form, name='reporte_form'),
    path('<int:id_company>/<str:criterio>/productos_pdf', views.reporte_inventario, name='inventario_productos'),
    path('<int:id_company>/info_address_company', views.info_address_company, name='info_address_company'),
    path('<int:id_address>/del_address_comp', views.del_address_comp, name='del_address_comp'),
    path('<int:id_company>/add_condiciones', views.add_condiciones, name='add_condiciones'),
    path('<int:id_company>/get_condiciones', views.get_condiciones, name='get_condiciones'),
    path('<int:id_regla>/delete_regla', views.delete_regla, name='delete_regla'),
    path('<int:id_company>/suscribirse/',  views.suscribirse, name='suscribirse'),
    path('<int:id_company>/add_cupon', views.add_cupon, name='add_cupon'),
    path('<int:id_company>/get_cupom', views.get_cupom, name='get_cupom'),
    path('<int:id_cupom>/delete_cupom', views.delete_cupom, name='delete_cupom'),
    path('<int:id_company>/estado_company/', views.estadoCompany, name='estado_company'),
    path('autorizar/<int:id_orden>/', views.autorizar_orden, name='autorizar_orden'),
]